### ISSUE TITLE
README 文件中中文标题与英文标题不符

### ISSUE THREAD

**Issue by yi-Xu-0100** [obster-y/XJTU-thesis-Office#3]
https://github.com/obster-y/XJTU-thesis-Office/blob/a65550d0b0db66e15f8ce8bd81ee368a5bd6e754/README.md#L1-L7

可以看出标题写的是 `西安交通大学学位论文模板-Office版`，但是英文是 `An unofficial Office Degree Thesis Template`，其后也是 `西安交通大学硕博学位论文的非官方 Microsoft-Word 模板`。后两个指明了此为非官方版本，是否应该改进标题为 `西安交通大学非官方学位论文模板-Office版`?

另外，是否应该给出 offical 版本的链接？或者说 http://gs.xjtu.edu.cn/info/1209/7605.htm 这个里面的 word 模板是西交大学校（官方）提供的标准参考？

**Comment by obster-y** [comment]
啊，这样写是有点怪，因为我是准备让他们把这个变成官方版的，但是学位办的人现在没怎么理我，所以这个模板目前确实是非官方版本。

标题没改，加了官方链接。
