### ISSUE TITLE
图表没有交叉引用

### ISSUE THREAD

**Issue by zyxhmt** [obster-y/XJTU-thesis-Office#4]
使用插入-文档部件-自动图文集 插入图或表后，在正文里使用交叉引用没有图表的

**Comment by obster-y** [comment]
[[@obster-y/xjtu-thesis-office](https://github.com/obster-y/XJTU-thesis-Office/7be4)](https://github.com/obster-y/XJTU-thesis-Office/commit/7be43de6bbc355c513711501dfb14c515a72c5a5)
