### ISSUE TITLE
自动图文集交叉引用问题

### ISSUE THREAD

**Issue by DerekLIN2023** [obster-y/XJTU-thesis-Office#5]
插入新的自动图文集之后，原来的交叉引用可能会定位到最新插入的自动图文集位置。

===

1. 把一个SEQ对象保存到自动图文集（比如图题/表题)，记为 a
2. 在正文中，通过自动图文集插入 a 得到对象 A
3. 在交叉引用里引用 A，得到引用对象 Ar
4. 再通过自动图文集插入一次 a 得到对象 B
5. 交叉引用 B 得到引用对象 Br
6. 此时 Ar 和 Br 指向的是同一个对象 B

**Comment by obster-y** [comment]
初步得到的理论是 Ar 引用的对象 A 是自动图文集里的对象 a，插入了 B 之后 A 不再是 a，而是变成了 A'，B 变成了 a，所以才会出现这种结果。感觉和 word 内更新「对象/域代码」的策略有关，或者和交叉引用的策略有关。

尚未找到一劳永逸的解决方法，曲线救国的方法是手动更新「对象id」(按推荐顺序排序)：
1. 插入完所有对象再引用(不多操作)
2. 插入两次再撤销一次插入(多一次插入操作，一次撤销操作)
3. 插入以后重新应用样式(多一次选中操作，一次应用样式操作)
4. 在自动图文集保存两个对象插入后删掉一个(多一次选中操作，一次删除操作)
