### ISSUE TITLE
关于英文目录页的页眉

### ISSUE THREAD

**Issue by JamesYXC** [obster-y/XJTU-thesis-Office#6]
当英文目录页在奇数页的时候，我发现上面的页眉显示的是ABSTRACT，打开域代码发现链接的是标题1，我重新下载模板生成还是这样，不清楚是我的word设置问题还是其他问题？
![issue](https://user-images.githubusercontent.com/39797718/230650575-d77d8c32-4288-43a0-8f99-f65274703518.png)

**Comment by obster-y** [comment]
刚看了，因为之前没有校验中文目录有偶数页的情况，所以是个失误。英文目录和后续之间插了分节符，所以可以先备份，再直接手动修改页眉试一下，应该是没问题的

实际上中文目录的页眉也是这么干的，因为严格意义上中英目录的一级标题都不是标题 1这个样式，所以直接引用到最前面的英文摘要去了
