### ISSUE TITLE
英文摘要页脚问题

### ISSUE THREAD

**Issue by zyxhmt** [obster-y/XJTU-thesis-Office#7]
英文摘要超过三页，在第一页添加基金支持后同步出现在第三页页脚处，在第三页页脚取消连接到前一节，删除后第一页页脚的也删除了

**Comment by obster-y** [comment]
1. 这不是模板的问题，而是你的使用问题
2. 很明显你的论文做了很多工作，才会超出学校要求中提到的 1000/800 字建议，如果遵守这个建议，应该不会出现第三页的问题
3. 我认为这是学校的要求有问题，表述为「在页脚处插入」应该为「使用脚注的方式插入」，具体操作请在 word 中点击「引用-插入脚注」
4. 如果非要在页脚插入，单纯从你描述的操作步骤来看是没有问题的，我不清楚为什么会出现这样的问题，这是非常具体的 word 操作问题，无法远程解答，建议询问身边的熟练使用者

**Comment by zyxhmt** [comment]
ok谢谢
